Vagrant.configure(2) do |config|

    config.vm.provision "shell", path: "bootstrap.sh"
    #config.vm.provision "shell", path: "configure.sh" -> file placed in /root/configure.sh
  
    # Ansible control node
    ControlNodeCount = 1
  
    (1..ControlNodeCount).each do |i|
  
      config.vm.define "ansible-0#{i}" do |cn|
  
        cn.vm.box                     = "ubuntu-24-04-server-ansible"
        cn.vm.box_check_update        = false
        cn.vm.box_version             = "0"
        cn.vm.hostname                = "ansible-0#{i}.example.com"
        
        #(removed 01.10.24)
        #cn.vm.network "private_network", ip: "192.168.0.10#{i}"
        #(added 01.10.24) - access via bridged network to host's network - turn off enp0s3 interface - and set default route for enp0s8 - by runinng ./setup.sh (as a root)
        cn.vm.network "public_network", ip: "192.168.1.10#{i}", bridge: "enp0s8: Intel(R) Ethernet Connection (11) I219-LM"
        
        cn.vm.provider :virtualbox do |v|
          v.name   = "ansible-0#{i}"
          v.memory = 4096
          v.cpus   = 2
      
        end

      end
  
    end
  
  
    # nodes managed by Ansible
    ManagedNodeCount = 2

    (1..ManagedNodeCount).each do |i|
  
      config.vm.define "vm-0#{i}" do |managednode|
  
        managednode.vm.box               = "ubuntu-24-04-server-ansible"
        managednode.vm.box_check_update  = false
        managednode.vm.box_version       = "0"
        managednode.vm.hostname          = "vm-0#{i}.example.com"
  
        #(removed 01.10.24)
        #managednode.vm.network "private_network", ip: "192.168.0.20#{i}"
        #(added 01.10.24) - access via bridged network to host's network - turn off enp0s3 interface - and set default route for enp0s8 - by runinng ./setup.sh (as a root)
        managednode.vm.network "public_network", ip: "192.168.1.20#{i}", bridge: "enp0s8: Intel(R) Ethernet Connection (11) I219-LM"
  

        managednode.vm.provider :virtualbox do |v|
          v.name   = "vm-0#{i}"
          v.memory = 2048
          v.cpus   = 2
 
        end

      end
  
    end
  
  end

