apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-15-awx-demo-postgres-15-0
  namespace: awx
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

