Vagrant.configure(2) do |config|
  
  # Kubernetes Master Nodes
  MasterCount = 1

  (1..MasterCount).each do |i|

    config.vm.define "master-0#{i}" do |masternode|

      masternode.vm.box               = "ubuntu-24-04-server-ext-storage"
      masternode.vm.box_check_update  = false
      masternode.vm.box_version       = "0"
      masternode.vm.hostname          = "master-0#{i}.example.com"
      masternode.vm.network "public_network", ip: "192.168.1.10#{i}", bridge: "Intel(R) Ethernet Connection (11) I219-LM"     
      masternode.vm.provider :virtualbox do |v|
        v.name   = "master-0#{i}"
        v.memory = 8192
        v.cpus   = 4

      end

    end

  end


  # Kubernetes Worker Nodes
  WorkerCount = 2

  (1..WorkerCount).each do |i|

    config.vm.define "worker-0#{i}" do |workernode|

      workernode.vm.box               = "ubuntu-24-04-server-ext-storage"
      workernode.vm.box_check_update  = false
      workernode.vm.box_version       = "0"
      workernode.vm.hostname          = "worker-0#{i}.example.com"
      workernode.vm.network "public_network", ip: "192.168.1.20#{i}", bridge: "Intel(R) Ethernet Connection (11) I219-LM"
      workernode.vm.provider :virtualbox do |v|
        v.name   = "worker-0#{i}"
        v.memory = 4096
        v.cpus   = 4

      end

    end

  end

end
