Vagrant.configure(2) do |config|

    # Load Balancer Nodes - Testing created image
    LoadBalancerCount = 1
  
    (1..LoadBalancerCount).each do |i|
  
      config.vm.define "lb-0#{i}" do |lb|
  
        lb.vm.box = "ubuntu-24-04-server-k8s"
        lb.vm.box_check_update  = false
        lb.vm.box_version       = "0"
        lb.vm.hostname          = "lb-0#{i}.example.com"
  
        #(removed 01.10.24)
        #lb.vm.network "private_network", ip: "192.168.0.5#{i}"
        #(added 01.10.24) - access via bridged network to host's network - turn off enp0s3 interface - and set default route for enp0s8 - by runinng ./setup.sh (as a root)
        lb.vm.network "public_network", ip: "192.168.1.5#{i}", bridge: "Intel(R) Ethernet Connection (11) I219-LM" 

        lb.vm.provider :virtualbox do |v|
          v.name   = "lb-0#{i}"
          v.memory = 2048
          v.cpus   = 2
      
        end

      end
  
    end
   
  end

