Vagrant.configure(2) do |config|

    config.vm.provision "file", source: "etc/haproxy/haproxy.conf", destination: "~/haproxy.conf"
    config.vm.provision "file", source: "etc/keepalived/keepalived.conf", destination: "~/keepalived.conf"
    config.vm.provision "file", source: "etc/keepalived/check_apiserver.sh", destination: "~/check_apiserver.sh"
    config.vm.provision "shell", path: "bootstrap.sh"
    #config.vm.provision "shell", path: "configure.sh" -> file placed in /root/configure.sh
  
    # Load Balancer Nodes
    LoadBalancerCount = 2
  
    (1..LoadBalancerCount).each do |i|
  
      config.vm.define "lb-0#{i}" do |lb|
  
        lb.vm.box = "ubuntu-24-04-server-k8s"
        lb.vm.box_check_update  = false
        lb.vm.box_version       = "0"
        lb.vm.hostname          = "lb-0#{i}.example.com"
  
        #lb.vm.base_address = "10.0.2.5#{i}"
        #lb.vm.network "public_network", ip: "10.0.2.5#{i}" - creates third network
        
        #(removed 01.10.24)
        #lb.vm.network "private_network", ip: "192.168.0.5#{i}"
        #(added 01.10.24) - access via bridged network to host's network - turn off enp0s3 interface - and set default route for enp0s8 - by runinng ./setup.sh (as a root)
        lb.vm.network "public_network", ip: "192.168.1.5#{i}", bridge: "enp0s8: Intel(R) Ethernet Connection (11) I219-LM"
  
        lb.vm.provider :virtualbox do |v|
          v.name   = "lb-0#{i}"
          v.memory = 2048
          v.cpus   = 2
      
        end

      end
  
    end
  
  
    # Kubernetes Master Nodes
    MasterCount = 3
  
    (1..MasterCount).each do |i|
  
      config.vm.define "master-0#{i}" do |masternode|
  
        masternode.vm.box               = "ubuntu-24-04-server-k8s"
        masternode.vm.box_check_update  = false
        masternode.vm.box_version       = "0"
        masternode.vm.hostname          = "master-0#{i}.example.com"
  
        #masternode.vm.base_address = "10.0.2.10#{i}"
        #masternode.vm.network "public_network", ip: "10.0.2.10#{i}"
        
        #(removed 01.10.24)
        #masternode.vm.network "private_network", ip: "192.168.0.10#{i}"
       #(added 01.10.24) - access via bridged network to host's network - turn off enp0s3 interface - and set default route for enp0s8 - by runinng ./setup.sh (as a root)
        masternode.vm.network "public_network", ip: "192.168.1.10#{i}", bridge: "enp0s8: Intel(R) Ethernet Connection (11) I219-LM"
  
        masternode.vm.provider :virtualbox do |v|
          v.name   = "master-0#{i}"
          v.memory = 2048
          v.cpus   = 2
 
        end

      end
  
    end
  
  
    # Kubernetes Worker Nodes
    WorkerCount = 1
  
    (1..WorkerCount).each do |i|
  
      config.vm.define "worker-0#{i}" do |workernode|
  
        workernode.vm.box               = "ubuntu-24-04-server-k8s"
        workernode.vm.box_check_update  = false
        workernode.vm.box_version       = "0"
        workernode.vm.hostname          = "worker-0#{i}.example.com"
  
        #workernode.vm.base_address = "10.0.2.20#{i}"
        #workernode.vm.network "public_network", ip: "10.0.2.20#{i}"
        
        #(removed 01.10.24)
        #workernode.vm.network "private_network", ip: "192.168.0.20#{i}"
        #(added 01.10.24) - access via bridged network to host's network - turn off enp0s3 interface - and set default route for enp0s8 - by runinng ./setup.sh (as a root)
        workernode.vm.network "public_network", ip: "192.168.1.20#{i}", bridge: "enp0s8: Intel(R) Ethernet Connection (11) I219-LM"
  
        workernode.vm.provider :virtualbox do |v|
          v.name   = "worker-0#{i}"
          v.memory = 2048
          v.cpus   = 2

        end
 
      end
  
    end
  
  end

