Vagrant.configure(2) do |config|

    config.vm.provision "shell", path: "set_spectrum_flag.sh"

    # Ansible control node
    ControlNodeCount = 1
  
    (1..ControlNodeCount).each do |i|
  
      config.vm.define "ansible-0#{i}" do |cn|
  
        cn.vm.box                     = "rhel-86-server-ansible"
        cn.vm.box_check_update        = false
        cn.vm.box_version             = "0"
        cn.vm.hostname                = "ansible-0#{i}"
        
        #(removed 01.10.24)
        #cn.vm.network "private_network", ip: "192.168.0.10#{i}"
        #(added 01.10.24) - access via bridged network to host's network - turn off enp0s3 interface - and set default route for enp0s8 - by runinng ./setup.sh (as a root)
        cn.vm.network "public_network", ip: "192.168.1.10#{i}", bridge: "Intel(R) Ethernet Connection (11) I219-LM"
        
        cn.vm.provider :virtualbox do |v|
          v.name   = "ansible-0#{i}"
          v.memory = 4096
          v.cpus   = 2
      
        end

      end
  
    end
  
  
    # LS landscapes managed by Ansible
    LandscapeCount = 2

    (1..LandscapeCount).each do |i|
  
      config.vm.define "ls-0#{i}" do |landscape|
  
        landscape.vm.box               = "rhel-86-server-ansible"
        landscape.vm.box_check_update  = false
        landscape.vm.box_version       = "0"
        landscape.vm.hostname          = "ls-0#{i}"
  
        #(removed 01.10.24)
        #managednode.vm.network "private_network", ip: "192.168.0.20#{i}"
        #(added 01.10.24) - access via bridged network to host's network - turn off enp0s3 interface - and set default route for enp0s8 - by runinng ./setup.sh (as a root)
        landscape.vm.network "public_network", ip: "192.168.1.20#{i}", bridge: "Intel(R) Ethernet Connection (11) I219-LM"
  

        landscape.vm.provider :virtualbox do |v|
          v.name   = "ls-0#{i}"
          v.memory = 2048
          v.cpus   = 2
 
        end

      end
  
    end

    # LSB - Landscapes Backup nodes managed by Ansible
    LandscapeBackupCount = 2

    (1..LandscapeBackupCount).each do |i|
  
      config.vm.define "lsb-0#{i}" do |landscapebackup|
  
      landscapebackup.vm.box               = "rhel-86-server-ansible"
      landscapebackup.vm.box_check_update  = false
      landscapebackup.vm.box_version       = "0"
      landscapebackup.vm.hostname          = "lsb-0#{i}"
  
        #(removed 01.10.24)
        #managednode.vm.network "private_network", ip: "192.168.0.20#{i}"
        #(added 01.10.24) - access via bridged network to host's network - turn off enp0s3 interface - and set default route for enp0s8 - by runinng ./setup.sh (as a root)
        landscapebackup.vm.network "public_network", ip: "192.168.1.21#{i}", bridge: "Intel(R) Ethernet Connection (11) I219-LM"
  

        landscapebackup.vm.provider :virtualbox do |v|
          v.name   = "lsb-0#{i}"
          v.memory = 2048
          v.cpus   = 2
 
        end

      end
  
    end

    # MLS - Main Location Server nodes managed by Ansible
    MlsCount = 2

    (1..MlsCount).each do |i|
  
      config.vm.define "mls-0#{i}" do |mls|
  
      mls.vm.box               = "rhel-86-server-ansible"
      mls.vm.box_check_update  = false
      mls.vm.box_version       = "0"
      mls.vm.hostname          = "mls-0#{i}"
  
        #(removed 01.10.24)
        #managednode.vm.network "private_network", ip: "192.168.0.20#{i}"
        #(added 01.10.24) - access via bridged network to host's network - turn off enp0s3 interface - and set default route for enp0s8 - by runinng ./setup.sh (as a root)
        mls.vm.network "public_network", ip: "192.168.1.5#{i}", bridge: "Intel(R) Ethernet Connection (11) I219-LM"
  

        mls.vm.provider :virtualbox do |v|
          v.name   = "mls-0#{i}"
          v.memory = 2048
          v.cpus   = 2
 
        end

      end
  
    end
  
  end

